DATA:
  run_name: ddpm_cifer
  dataset_path: /content/Diffusion-Models-pytorch-module-compile-yaml/datasets/cifar10-64/train
  num_classes: 10
  image_size: 64
  day: ddpm_cifer_day

MODEL:
  unet: UNet_conditional
  ema: EMA

TRAIN:
  batch_size: 8
  device: cuda
  epochs: 300
  lr: 0.0003
  multigpu: false
  scheulder: false
  seed: 111
